version: '3.9'

services:
  zookeeper:
    image: zookeeper:3.8  # Updated version
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "8080:8080"
      - "4040:4040"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark:7077
    volumes:
      - ./app:/app

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__DATABASE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////root/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./airflow_logs:/opt/airflow/logs
    entrypoint: ["/bin/bash", "-c", "airflow db init && airflow webserver & airflow scheduler"]
